# Generated by Django 5.1.5 on 2025-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_processo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado',
            field=models.CharField(default='Geral', max_length=100),
        ),
    ]
