# Generated by Django 4.2.20 on 2025-03-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_citiusaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='citiusaccount',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
