# Generated by Django 4.2.20 on 2025-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_citiusaccount_user_processo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='document_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='document_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
