# Generated by Django 4.2.20 on 2025-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_processo_document_size_processo_document_stored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='document_stored',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
