# Generated by Django 4.2.20 on 2025-04-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_processo_document_stored'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiusAccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to='api.citiusaccount')),
            ],
            options={
                'unique_together': {('account', 'email')},
            },
        ),
    ]
