# Generated by Django 4.2.21 on 2025-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_processo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('accounts_status', models.JSONField(blank=True, default=dict, null=True)),
                ('document_errors', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status do Sistema',
                'verbose_name_plural': 'Status do Sistema',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='document_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='document_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('error', 'Erro')], default='pending', max_length=20),
        ),
    ]
