# Generated by Django 4.2.21 on 2025-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_systemstatus_processo_document_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
