services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres.shzvugthjndlagxlcowp:datapostgressql@aws-0-eu-west-3.pooler.supabase.com:5432/postgres
      - SUPABASE_URL=https://shzvugthjndlagxlcowp.supabase.co
      - SUPABASE_SECRET_KEY=your_supabase_secret_key
      - SUPABASE_ACCESS_KEY=your_supabase_access_key
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers=2 --threads=2 --timeout=120
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - CELERYD_HIJACK_ROOT_LOGGER=False
      - TZ=Europe/Lisbon
      - DATABASE_URL=postgresql://postgres.shzvugthjndlagxlcowp:datapostgressql@aws-0-eu-west-3.pooler.supabase.com:5432/postgres
      - SUPABASE_URL=https://shzvugthjndlagxlcowp.supabase.co
      - SUPABASE_SECRET_KEY=your_supabase_secret_key
      - SUPABASE_ACCESS_KEY=your_supabase_access_key
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    command: bash -c "nice -n -20 celery -A backend worker -l info --concurrency=$(nproc) --prefetch-multiplier=1"
    networks:
      - app-network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - CELERYD_HIJACK_ROOT_LOGGER=False
      - TZ=Europe/Lisbon
      - DATABASE_URL=postgresql://postgres.shzvugthjndlagxlcowp:datapostgressql@aws-0-eu-west-3.pooler.supabase.com:5432/postgres
      - SUPABASE_URL=https://shzvugthjndlagxlcowp.supabase.co
      - SUPABASE_SECRET_KEY=your_supabase_secret_key
      - SUPABASE_ACCESS_KEY=your_supabase_access_key
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --max-interval=30
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always
    command: redis-server --save 20 1 --maxmemory 100mb --maxmemory-policy allkeys-lru

networks:
  app-network:
    driver: bridge